name: Classroom Autograding
on:
  push:
  workflow_dispatch:

jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install pytest
      - name: Run autograder
        uses: education/autograding@v1
